trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboards.yml@templates
    parameters:
      name: mns
      packageName: keyboard-mns
      kbdgenFolder: "mns.kbdgen"
      repositoryWin: "https://pahkat.uit.no/repo/misc-win"
      repositoryMac: "https://pahkat.uit.no/repo/misc-macos"
      languages:
        - projectjjName: giella-mns
          path: usr/share/giella/mobilespellers/mns-mobile.zhfst
          name: mns
