template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 23
template_sha = "4c943b609dddca98aa904e9be25e77177ceb8edd"

[replacements]
__UND2C__ = "mns"
__UNDEFINED__ = "Mansi"
__UND__ = "mns"
